-- Datapath (Auto-Generated)
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;
use std.textio.all;

entity Datapath is
    generic (DATA_WIDTH : integer := 32; ADDR_WIDTH : integer := 10);
    Port ( clk, rst : in STD_LOGIC;
           R0_en : in STD_LOGIC;
           R1_en : in STD_LOGIC;
           R10_en : in STD_LOGIC;
           R11_en : in STD_LOGIC;
           R12_en : in STD_LOGIC;
           R13_en : in STD_LOGIC;
           R14_en : in STD_LOGIC;
           R15_en : in STD_LOGIC;
           R16_en : in STD_LOGIC;
           R17_en : in STD_LOGIC;
           R18_en : in STD_LOGIC;
           R19_en : in STD_LOGIC;
           R2_en : in STD_LOGIC;
           R20_en : in STD_LOGIC;
           R21_en : in STD_LOGIC;
           R22_en : in STD_LOGIC;
           R23_en : in STD_LOGIC;
           R24_en : in STD_LOGIC;
           R25_en : in STD_LOGIC;
           R26_en : in STD_LOGIC;
           R27_en : in STD_LOGIC;
           R28_en : in STD_LOGIC;
           R29_en : in STD_LOGIC;
           R3_en : in STD_LOGIC;
           R30_en : in STD_LOGIC;
           R31_en : in STD_LOGIC;
           R32_en : in STD_LOGIC;
           R33_en : in STD_LOGIC;
           R34_en : in STD_LOGIC;
           R35_en : in STD_LOGIC;
           R36_en : in STD_LOGIC;
           R37_en : in STD_LOGIC;
           R38_en : in STD_LOGIC;
           R39_en : in STD_LOGIC;
           R4_en : in STD_LOGIC;
           R40_en : in STD_LOGIC;
           R41_en : in STD_LOGIC;
           R42_en : in STD_LOGIC;
           R43_en : in STD_LOGIC;
           R44_en : in STD_LOGIC;
           R45_en : in STD_LOGIC;
           R46_en : in STD_LOGIC;
           R47_en : in STD_LOGIC;
           R48_en : in STD_LOGIC;
           R49_en : in STD_LOGIC;
           R5_en : in STD_LOGIC;
           R50_en : in STD_LOGIC;
           R51_en : in STD_LOGIC;
           R52_en : in STD_LOGIC;
           R53_en : in STD_LOGIC;
           R54_en : in STD_LOGIC;
           R55_en : in STD_LOGIC;
           R56_en : in STD_LOGIC;
           R57_en : in STD_LOGIC;
           R58_en : in STD_LOGIC;
           R59_en : in STD_LOGIC;
           R6_en : in STD_LOGIC;
           R60_en : in STD_LOGIC;
           R61_en : in STD_LOGIC;
           R62_en : in STD_LOGIC;
           R63_en : in STD_LOGIC;
           R64_en : in STD_LOGIC;
           R65_en : in STD_LOGIC;
           R66_en : in STD_LOGIC;
           R67_en : in STD_LOGIC;
           R68_en : in STD_LOGIC;
           R69_en : in STD_LOGIC;
           R7_en : in STD_LOGIC;
           R70_en : in STD_LOGIC;
           R71_en : in STD_LOGIC;
           R8_en : in STD_LOGIC;
           R9_en : in STD_LOGIC;
           A_en : in STD_LOGIC;
           A_wr : in STD_LOGIC;
           C_en : in STD_LOGIC;
           C_wr : in STD_LOGIC;
           W_en : in STD_LOGIC;
           W_wr : in STD_LOGIC;
           Mux_A_addr_sel : in STD_LOGIC_VECTOR(3 downto 0);
           Mux_Add_0_left_sel : in STD_LOGIC_VECTOR(3 downto 0);
           Mux_Add_0_right_sel : in STD_LOGIC_VECTOR(3 downto 0);
           Mux_C_addr_sel : in STD_LOGIC_VECTOR(3 downto 0);
           Mux_C_data_sel : in STD_LOGIC_VECTOR(3 downto 0);
           Mux_Mul_0_left_sel : in STD_LOGIC_VECTOR(3 downto 0);
           Mux_Mul_0_right_sel : in STD_LOGIC_VECTOR(3 downto 0);
           Mux_W_addr_sel : in STD_LOGIC_VECTOR(3 downto 0);
           done : out STD_LOGIC);
end Datapath;

architecture Behavioral of Datapath is
    -- Registers
    signal R0_out : INTEGER := 0;
    signal R1_out : INTEGER := 0;
    signal R10_out : INTEGER := 0;
    signal R11_out : INTEGER := 0;
    signal R12_out : INTEGER := 0;
    signal R13_out : INTEGER := 0;
    signal R14_out : INTEGER := 0;
    signal R15_out : INTEGER := 0;
    signal R16_out : INTEGER := 0;
    signal R17_out : INTEGER := 0;
    signal R18_out : INTEGER := 0;
    signal R19_out : INTEGER := 0;
    signal R2_out : INTEGER := 0;
    signal R20_out : INTEGER := 0;
    signal R21_out : INTEGER := 0;
    signal R22_out : INTEGER := 0;
    signal R23_out : INTEGER := 0;
    signal R24_out : INTEGER := 0;
    signal R25_out : INTEGER := 0;
    signal R26_out : INTEGER := 0;
    signal R27_out : INTEGER := 0;
    signal R28_out : INTEGER := 0;
    signal R29_out : INTEGER := 0;
    signal R3_out : INTEGER := 0;
    signal R30_out : INTEGER := 0;
    signal R31_out : INTEGER := 0;
    signal R32_out : INTEGER := 0;
    signal R33_out : INTEGER := 0;
    signal R34_out : INTEGER := 0;
    signal R35_out : INTEGER := 0;
    signal R36_out : INTEGER := 0;
    signal R37_out : INTEGER := 0;
    signal R38_out : INTEGER := 0;
    signal R39_out : INTEGER := 0;
    signal R4_out : INTEGER := 0;
    signal R40_out : INTEGER := 0;
    signal R41_out : INTEGER := 0;
    signal R42_out : INTEGER := 0;
    signal R43_out : INTEGER := 0;
    signal R44_out : INTEGER := 0;
    signal R45_out : INTEGER := 0;
    signal R46_out : INTEGER := 0;
    signal R47_out : INTEGER := 0;
    signal R48_out : INTEGER := 0;
    signal R49_out : INTEGER := 0;
    signal R5_out : INTEGER := 0;
    signal R50_out : INTEGER := 0;
    signal R51_out : INTEGER := 0;
    signal R52_out : INTEGER := 0;
    signal R53_out : INTEGER := 0;
    signal R54_out : INTEGER := 0;
    signal R55_out : INTEGER := 0;
    signal R56_out : INTEGER := 0;
    signal R57_out : INTEGER := 0;
    signal R58_out : INTEGER := 0;
    signal R59_out : INTEGER := 0;
    signal R6_out : INTEGER := 0;
    signal R60_out : INTEGER := 0;
    signal R61_out : INTEGER := 0;
    signal R62_out : INTEGER := 0;
    signal R63_out : INTEGER := 0;
    signal R64_out : INTEGER := 0;
    signal R65_out : INTEGER := 0;
    signal R66_out : INTEGER := 0;
    signal R67_out : INTEGER := 0;
    signal R68_out : INTEGER := 0;
    signal R69_out : INTEGER := 0;
    signal R7_out : INTEGER := 0;
    signal R70_out : INTEGER := 0;
    signal R71_out : INTEGER := 0;
    signal R8_out : INTEGER := 0;
    signal R9_out : INTEGER := 0;
    -- Mux outputs
    signal Mux_A_addr_out : INTEGER := 0;
    signal Mux_W_addr_out : INTEGER := 0;
    signal Mux_Mul_0_left_out : INTEGER := 0;
    signal Mux_Mul_0_right_out : INTEGER := 0;
    signal Mux_Add_0_left_out : INTEGER := 0;
    signal Mux_Add_0_right_out : INTEGER := 0;
    signal Mux_C_addr_out : INTEGER := 0;
    signal Mux_C_data_out : INTEGER := 0;
    -- Memory outputs
    signal A_dout : INTEGER := 0;
    signal C_dout : INTEGER := 0;
    signal W_dout : INTEGER := 0;
    -- Arithmetic outputs
    signal Add_0_out : INTEGER := 0;
    signal Mul_0_out : INTEGER := 0;
    type ram_array is array (0 to 2**ADDR_WIDTH-1) of INTEGER;
    impure function init_ram(filename : string) return ram_array is
        file f : text; variable l : line; variable v : integer; variable r : ram_array; variable s : file_open_status;
    begin
        for i in r'range loop r(i) := 0; end loop;
        file_open(s, f, filename, read_mode);
        if s = open_ok then
            for i in r'range loop if not endfile(f) then readline(f, l); read(l, v); r(i) := v; end if; end loop;
            file_close(f);
        end if;
        return r;
    end function;
    signal A_mem : ram_array := init_ram("A_content.txt");
    signal C_mem : ram_array := init_ram("C_content.txt");
    signal W_mem : ram_array := init_ram("W_content.txt");

begin
    done <= '1';

    process(clk) begin
        if rising_edge(clk) then
            if R0_en = '1' then R0_out <= 0; end if;
            if R1_en = '1' then R1_out <= 0; end if;
            if R10_en = '1' then R10_out <= 2; end if;
            if R11_en = '1' then R11_out <= 2; end if;
            if R12_en = '1' then R12_out <= A_dout; end if;
            if R13_en = '1' then R13_out <= W_dout; end if;
            if R14_en = '1' then R14_out <= Add_0_out; end if;
            if R15_en = '1' then R15_out <= Mul_0_out; end if;
            if R16_en = '1' then R16_out <= 0; end if;
            if R17_en = '1' then R17_out <= Add_0_out; end if;
            if R18_en = '1' then R18_out <= 1; end if;
            if R19_en = '1' then R19_out <= 0; end if;
            if R2_en = '1' then R2_out <= A_dout; end if;
            if R20_en = '1' then R20_out <= A_dout; end if;
            if R21_en = '1' then R21_out <= W_dout; end if;
            if R22_en = '1' then R22_out <= 2; end if;
            if R23_en = '1' then R23_out <= 1; end if;
            if R24_en = '1' then R24_out <= A_dout; end if;
            if R25_en = '1' then R25_out <= W_dout; end if;
            if R26_en = '1' then R26_out <= Mul_0_out; end if;
            if R27_en = '1' then R27_out <= Mul_0_out; end if;
            if R28_en = '1' then R28_out <= 3; end if;
            if R29_en = '1' then R29_out <= 2; end if;
            if R3_en = '1' then R3_out <= W_dout; end if;
            if R30_en = '1' then R30_out <= A_dout; end if;
            if R31_en = '1' then R31_out <= W_dout; end if;
            if R32_en = '1' then R32_out <= Add_0_out; end if;
            if R33_en = '1' then R33_out <= Mul_0_out; end if;
            if R34_en = '1' then R34_out <= 1; end if;
            if R35_en = '1' then R35_out <= Add_0_out; end if;
            if R36_en = '1' then R36_out <= 2; end if;
            if R37_en = '1' then R37_out <= 0; end if;
            if R38_en = '1' then R38_out <= A_dout; end if;
            if R39_en = '1' then R39_out <= W_dout; end if;
            if R4_en = '1' then R4_out <= 1; end if;
            if R40_en = '1' then R40_out <= 3; end if;
            if R41_en = '1' then R41_out <= 1; end if;
            if R42_en = '1' then R42_out <= A_dout; end if;
            if R43_en = '1' then R43_out <= W_dout; end if;
            if R44_en = '1' then R44_out <= Mul_0_out; end if;
            if R45_en = '1' then R45_out <= Mul_0_out; end if;
            if R46_en = '1' then R46_out <= 4; end if;
            if R47_en = '1' then R47_out <= 2; end if;
            if R48_en = '1' then R48_out <= A_dout; end if;
            if R49_en = '1' then R49_out <= W_dout; end if;
            if R5_en = '1' then R5_out <= 1; end if;
            if R50_en = '1' then R50_out <= Add_0_out; end if;
            if R51_en = '1' then R51_out <= Mul_0_out; end if;
            if R52_en = '1' then R52_out <= 2; end if;
            if R53_en = '1' then R53_out <= Add_0_out; end if;
            if R54_en = '1' then R54_out <= 3; end if;
            if R55_en = '1' then R55_out <= 0; end if;
            if R56_en = '1' then R56_out <= A_dout; end if;
            if R57_en = '1' then R57_out <= W_dout; end if;
            if R58_en = '1' then R58_out <= 4; end if;
            if R59_en = '1' then R59_out <= 1; end if;
            if R6_en = '1' then R6_out <= A_dout; end if;
            if R60_en = '1' then R60_out <= A_dout; end if;
            if R61_en = '1' then R61_out <= W_dout; end if;
            if R62_en = '1' then R62_out <= Mul_0_out; end if;
            if R63_en = '1' then R63_out <= Mul_0_out; end if;
            if R64_en = '1' then R64_out <= 5; end if;
            if R65_en = '1' then R65_out <= 2; end if;
            if R66_en = '1' then R66_out <= A_dout; end if;
            if R67_en = '1' then R67_out <= W_dout; end if;
            if R68_en = '1' then R68_out <= Add_0_out; end if;
            if R69_en = '1' then R69_out <= Mul_0_out; end if;
            if R7_en = '1' then R7_out <= W_dout; end if;
            if R70_en = '1' then R70_out <= 3; end if;
            if R71_en = '1' then R71_out <= Add_0_out; end if;
            if R8_en = '1' then R8_out <= Mul_0_out; end if;
            if R9_en = '1' then R9_out <= Mul_0_out; end if;
        end if;
    end process;

    Mux_A_addr_out <= R0_out when Mux_A_addr_sel = "0000" else R4_out when Mux_A_addr_sel = "0001" else R10_out when Mux_A_addr_sel = "0010" else R18_out when Mux_A_addr_sel = "0011" else R22_out when Mux_A_addr_sel = "0100" else R28_out when Mux_A_addr_sel = "0101" else R36_out when Mux_A_addr_sel = "0110" else R40_out when Mux_A_addr_sel = "0111" else R46_out when Mux_A_addr_sel = "1000" else R54_out when Mux_A_addr_sel = "1001" else R58_out when Mux_A_addr_sel = "1010" else R64_out when Mux_A_addr_sel = "1011" else 0;
    Mux_W_addr_out <= R1_out when Mux_W_addr_sel = "0000" else R5_out when Mux_W_addr_sel = "0001" else R11_out when Mux_W_addr_sel = "0010" else R19_out when Mux_W_addr_sel = "0011" else R23_out when Mux_W_addr_sel = "0100" else R29_out when Mux_W_addr_sel = "0101" else R37_out when Mux_W_addr_sel = "0110" else R41_out when Mux_W_addr_sel = "0111" else R47_out when Mux_W_addr_sel = "1000" else R55_out when Mux_W_addr_sel = "1001" else R59_out when Mux_W_addr_sel = "1010" else R65_out when Mux_W_addr_sel = "1011" else 0;
    Mux_Mul_0_left_out <= R2_out when Mux_Mul_0_left_sel = "0000" else R6_out when Mux_Mul_0_left_sel = "0001" else R12_out when Mux_Mul_0_left_sel = "0010" else R20_out when Mux_Mul_0_left_sel = "0011" else R24_out when Mux_Mul_0_left_sel = "0100" else R30_out when Mux_Mul_0_left_sel = "0101" else R38_out when Mux_Mul_0_left_sel = "0110" else R42_out when Mux_Mul_0_left_sel = "0111" else R48_out when Mux_Mul_0_left_sel = "1000" else R56_out when Mux_Mul_0_left_sel = "1001" else R60_out when Mux_Mul_0_left_sel = "1010" else R66_out when Mux_Mul_0_left_sel = "1011" else 0;
    Mux_Mul_0_right_out <= R3_out when Mux_Mul_0_right_sel = "0000" else R7_out when Mux_Mul_0_right_sel = "0001" else R13_out when Mux_Mul_0_right_sel = "0010" else R21_out when Mux_Mul_0_right_sel = "0011" else R25_out when Mux_Mul_0_right_sel = "0100" else R31_out when Mux_Mul_0_right_sel = "0101" else R39_out when Mux_Mul_0_right_sel = "0110" else R43_out when Mux_Mul_0_right_sel = "0111" else R49_out when Mux_Mul_0_right_sel = "1000" else R57_out when Mux_Mul_0_right_sel = "1001" else R61_out when Mux_Mul_0_right_sel = "1010" else R67_out when Mux_Mul_0_right_sel = "1011" else 0;
    Mux_Add_0_left_out <= R8_out when Mux_Add_0_left_sel = "0000" else R14_out when Mux_Add_0_left_sel = "0001" else R26_out when Mux_Add_0_left_sel = "0010" else R32_out when Mux_Add_0_left_sel = "0011" else R44_out when Mux_Add_0_left_sel = "0100" else R50_out when Mux_Add_0_left_sel = "0101" else R62_out when Mux_Add_0_left_sel = "0110" else R68_out when Mux_Add_0_left_sel = "0111" else 0;
    Mux_Add_0_right_out <= R9_out when Mux_Add_0_right_sel = "0000" else R15_out when Mux_Add_0_right_sel = "0001" else R27_out when Mux_Add_0_right_sel = "0010" else R33_out when Mux_Add_0_right_sel = "0011" else R45_out when Mux_Add_0_right_sel = "0100" else R51_out when Mux_Add_0_right_sel = "0101" else R63_out when Mux_Add_0_right_sel = "0110" else R69_out when Mux_Add_0_right_sel = "0111" else 0;
    Mux_C_addr_out <= R16_out when Mux_C_addr_sel = "0000" else R34_out when Mux_C_addr_sel = "0001" else R52_out when Mux_C_addr_sel = "0010" else R70_out when Mux_C_addr_sel = "0011" else 0;
    Mux_C_data_out <= R17_out when Mux_C_data_sel = "0000" else R35_out when Mux_C_data_sel = "0001" else R53_out when Mux_C_data_sel = "0010" else R71_out when Mux_C_data_sel = "0011" else 0;

    A_dout <= A_mem(Mux_A_addr_out);
    C_dout <= C_mem(Mux_C_addr_out);
    W_dout <= W_mem(Mux_W_addr_out);

    process(clk) begin if rising_edge(clk) then if C_wr = '1' then C_mem(Mux_C_addr_out) <= Mux_C_data_out; end if; end if; end process;

    Mul_0_out <= Mux_Mul_0_left_out * Mux_Mul_0_right_out;
    Add_0_out <= Mux_Add_0_left_out + Mux_Add_0_right_out;

end Behavioral;